"""Render Three.js IK snapshots generated by node tools/verifyArms.mjs."""
import bpy, json
from pathlib import Path
from mathutils import Vector, Matrix
ROOT=Path(__file__).resolve().parents[1]
A=Matrix(((1,0,0),(0,0,-1),(0,1,0)))
for snapshot in json.loads((ROOT/'previews/arms-poses.json').read_text()):
    bpy.ops.object.select_all(action='SELECT');bpy.ops.object.delete(use_global=False)
    for m in snapshot['meshes']:
        mesh=bpy.data.meshes.new(m['name'])
        mesh.from_pydata([A@Vector(v) for v in m['vertices']],[],[m['indices'][i:i+3] for i in range(0,len(m['indices']),3)])
        mesh.update()
        obj=bpy.data.objects.new(m['name'],mesh);bpy.context.collection.objects.link(obj)
        mat=bpy.data.materials.new(m['name']);mat.diffuse_color=(*m['color'],1)
        mat.use_nodes=True
        shader=mat.node_tree.nodes.get('Principled BSDF')
        shader.inputs['Base Color'].default_value=(*m['color'],1)
        shader.inputs['Roughness'].default_value=.7
        mesh.materials.append(mat)
        for p in mesh.polygons:p.use_smooth=True
    scene=bpy.context.scene
    camdata=bpy.data.cameras.new('First person');cam=bpy.data.objects.new('First person',camdata)
    bpy.context.collection.objects.link(cam)
    cam.location=A@Vector((0,0,.10))
    cam.rotation_euler=(A@Vector((0,-.18,-1))-cam.location).to_track_quat('-Z','Y').to_euler()
    camdata.lens=18;scene.camera=cam
    for pos,power,size in [((-.8,1,.5),110,2),((1,.2,-1),80,1.5)]:
        data=bpy.data.lights.new('Softbox','AREA');data.energy=power;data.size=size
        obj=bpy.data.objects.new('Softbox',data);bpy.context.collection.objects.link(obj)
        obj.location=A@Vector(pos);obj.rotation_euler=(A@Vector((0,-.3,-.4))-obj.location).to_track_quat('-Z','Y').to_euler()
    scene.render.engine='CYCLES';scene.cycles.samples=16
    scene.render.resolution_x=960;scene.render.resolution_y=640;scene.render.resolution_percentage=100
    scene.world.color=(.06,.08,.11)
    scene.render.filepath=str(ROOT/f"previews/rig-{snapshot['id']}.png")
    bpy.ops.render.render(write_still=True)
