import { SKILL_TASKS } from './skillTasks.js';

const guide = (title, purpose, steps, mistake, improve, goal, target = {}) =>
  ({ title, purpose, steps, mistake, improve, goal, target });
export const TASK_GUIDES = Object.freeze({
  gridshot: guide('Gridshot', 'Aquecimento de transições entre alvos; a velocidade daqui não representa sozinha a qualidade do primeiro tiro em Valorant.', ['Olhe o próximo alvo antes de mover a mira.', 'Faça o deslocamento e confirme dentro da esfera.', 'Clique uma vez e já escolha o próximo alvo.'], 'Acelerar e clicar antes de confirmar.', 'Mantenha a precisão e reduza aos poucos o tempo parado entre os alvos.', '90% em pelo menos 20 tiros.', { accuracy: 90, shots: 20 }),
  microshot: guide('Microshot', 'Pequenas correções do primeiro tiro e controle fino em distâncias longas.', ['Deixe a mão leve.', 'Leve a mira para perto do pequeno alvo.', 'Complete a correção e clique sem arrastar um spray.'], 'Passar do alvo e fazer várias correções grandes.', 'Reduza o tamanho da correção final; aumente a velocidade após três sessões precisas.', '90% em pelo menos 15 tiros.', { accuracy: 90, shots: 15 }),
  tracking: guide('Strafe Track', 'Manter o alinhamento horizontal enquanto um adversário se desloca.', ['Observe a velocidade do alvo.', 'Acompanhe sem saltos grandes da mira.', 'Confirme cada disparo e responda às inversões.'], 'Antecipar demais e ficar à frente do alvo.', 'Faça correções menores nas inversões e compare a precisão na mesma dificuldade.', '85% em pelo menos 15 tiros.', { accuracy: 85, shots: 15 }),
  voltaic_static: guide('1w6ts Static', 'Cadência estável, seleção do próximo alvo e precisão de cliques isolados.', ['Escolha uma ordem de alvos.', 'Faça flick, microajuste e clique.', 'Repita em ritmo uniforme, com pouco tempo de hesitação.'], 'Flick rápido seguido de uma pausa longa e tensa.', 'Use a task de metrônomo e depois retire a ajuda mantendo o mesmo ritmo.', '95% em pelo menos 20 tiros.', { accuracy: 95, shots: 20 }),
  voltaic_pasu: guide('Pasu Dynamic', 'Confirmar a mira em alvos que mudam de trajetória; complementa as tasks horizontais.', ['Observe o movimento antes de escolher o alvo.', 'Aproxime a mira acompanhando a velocidade.', 'Clique quando o alinhamento estiver confirmado.'], 'Atirar na posição anterior da esfera.', 'Treine mais devagar até reduzir os erros; depois use alvos menores.', '85% em pelo menos 15 tiros.', { accuracy: 85, shots: 15 }),
  voltaic_smooth: guide('Smoothbot 3D', 'Tracking contínuo e controle de tensão em trajetórias amplas.', ['Acompanhe o orbe sem precisar atirar.', 'Use o braço nas partes amplas e a mão nas correções.', 'Mantenha pressão leve mesmo quando mudar a direção.'], 'Tentar corrigir cada frame com um flick.', 'Compare a cobertura ao longo de três rounds, usando a mesma sensibilidade.', '60% de cobertura por pelo menos 30 s.', { accuracy: 60, seconds: 30 }),
  voltaic_switch: guide('Target Switch', 'Transferir entre alvos móveis com rapidez depois da eliminação.', ['Escolha o alvo mais próximo do seu alinhamento.', 'Confirme e elimine.', 'Saia imediatamente para outro alvo ativo.'], 'Continuar atirando na posição de um alvo já eliminado.', 'Priorize transições curtas e precisão antes de ampliar o campo.', '85% em pelo menos 20 tiros.', { accuracy: 85, shots: 20 }),
  hold_pixel: guide('Angle Hold', 'Reagir à passagem contínua pelo ângulo com crosshair placement.', ['Escolha A Main, Heaven, Fresta ou Aleatório.', 'Deixe a mira na altura da cabeça e um pouco afastada da quina.', 'Espere a passagem e confirme o tiro.'], 'Atirar antes de ver o alvo ou perseguir a parede com a mira.', 'Ajuste o afastamento da quina à velocidade; reduza sua reação mantendo precisão.', '85% em pelo menos 10 tiros.', { accuracy: 85, shots: 10 }),
  drones: guide('Drone Survival', 'Dividir atenção entre tracking, eliminação e desvio de projéteis.', ['Use as setas para localizar drones fora da visão.', 'Olhe o laser de aviso e prepare o desvio.', 'Elimine com um tiro, reposicionando-se entre ataques.'], 'Ficar parado no tracking e ignorar o projétil.', 'Mantenha trajetórias laterais curtas; suba a dificuldade depois de sobreviver a um round.', 'Concluir vivo com pelo menos 8 eliminações.', { kills: 8, victory: true }),
  jett_neon: guide('Jett & Neon Dodge', 'Acompanhar passes aéreos e slides enquanto desvia de ataques.', ['Identifique se o movimento é aéreo ou rasteiro.', 'Desvie da linha do ataque.', 'Confirme o alvo durante a passagem.'], 'Usar a mesma altura de mira para os dois agentes.', 'Pratique uma correção vertical menor para Neon e acompanhe o arco da Jett.', 'Concluir vivo com pelo menos 6 eliminações.', { kills: 6, victory: true }),
  anti_rush: guide('Anti-Rush • Ascent A', 'Defender o site, priorizar utilidades e punir o entry usando cobertura.', ['Posicione-se em Generator, Dice, Hell ou outra cobertura do site.', 'Quebre drone, recon e flash quando aparecerem.', 'Observe o dash e a saída da smoke; elimine os entries sem abandonar o site.'], 'Olhar só para a Jett e deixar as utilidades ativas.', 'Mude de posição após o contato, corte linhas de visão e compare utilidades quebradas entre rounds.', 'Concluir vivo com pelo menos 5 eliminações.', { kills: 5, victory: true }),
  pokeball: guide(SKILL_TASKS.pokeball.title, 'Confirmar a mira e evitar cliques feitos durante um flick sem controle.', ['Em Auto Small, acompanhe até completar a barra.', 'Em Frenzy, mantenha a mira e faça três cliques cadenciados.', 'Recomece a confirmação se sair do alvo.'], 'Confundir chegar perto com confirmar dentro da hitbox.', 'Busque continuidade de tracking; compare cobertura em Auto e precisão em Frenzy.', '75% de cobertura em Auto ou 85% e 15 tiros em Frenzy.', { accuracy: 75, seconds: 30, shots: 15, autoOrClick: true }),
  horizontal_clicking: guide(SKILL_TASKS.horizontal_clicking.title, 'Punir a frenagem de um jiggle ou counter-strafe humano.', ['Mantenha a mira na linha dos olhos.', 'Acompanhe o strafe curto.', 'Clique na frenagem; a parada rende bônus.'], 'Fazer correção vertical sem o alvo mudar de altura.', 'Reduza overshoot nas inversões e mantenha a mira na mesma linha.', '90% em pelo menos 15 tiros.', { accuracy: 90, shots: 15 }),
  voxts: guide(SKILL_TASKS.voxts.title, 'Transferir entre inimigos com pouca vida sem perder a confirmação.', ['Acompanhe a barra de vida.', 'Complete os acertos necessários.', 'Troque de alvo assim que eliminar, aproveitando o bônus de transição.'], 'Trocar antes da eliminação ou esperar o respawn na mesma faixa.', 'Compare o tempo médio de transição sem reduzir a precisão.', '85% em pelo menos 20 tiros.', { accuracy: 85, shots: 20 }),
  reflex_micro: guide(SKILL_TASKS.reflex_micro.title, 'Correção rápida perto do crosshair placement.', ['Volte à âncora central.', 'Espere o alvo aparecer perto dela.', 'Faça uma correção pequena e clique antes do prazo.'], 'Antecipar o spawn sem olhar a posição real.', 'Reduza alvos perdidos mantendo precisão; comece no Fácil.', '85% em pelo menos 10 tentativas.', { accuracy: 85, shots: 10 }),
  wall_two: guide(SKILL_TASKS.wall_two.title, 'Flick inicial e correção fina em dois duelos sem poluição visual.', ['Escolha uma das duas esferas.', 'Aproxime, corrija e confirme.', 'Elimine a segunda e acompanhe o reset da dupla.'], 'Clicar em sequência sem completar a correção do segundo alvo.', 'Compare a cadência de duplas com no máximo um erro por round.', '95% em pelo menos 20 tiros.', { accuracy: 95, shots: 20 }),
  centering: guide(SKILL_TASKS.centering.title, 'Estabilizar a mira perto do centro e observar tremor nas inversões.', ['Acompanhe sem disparar.', 'Evite apertar a mão quando o alvo muda a direção.', 'Comece em Centering I e use II para variações mais rápidas.'], 'Travar o braço e corrigir só com pequenos saltos.', 'Use a cobertura como referência, repetindo a mesma variante antes de avançar.', '70% de cobertura por 30 s.', { accuracy: 70, seconds: 30 }),
  controlsphere: guide(SKILL_TASKS.controlsphere.title, 'Movimentos amplos com braço e antebraço; Thin separa a estabilidade horizontal.', ['Acompanhe o arco usando o braço.', 'Corrija com a mão perto das inversões.', 'Use Thin para observar a oscilação vertical.'], 'Apertar o mouse ou levantar a mira em arcos horizontais.', 'Compare cobertura com o mesmo campo de movimento antes de aumentar a velocidade.', '60% de cobertura por 30 s.', { accuracy: 60, seconds: 30 }),
  vertical_strafes: guide(SKILL_TASKS.vertical_strafes.title, 'Ajustar altura e profundidade contra mobilidade vertical.', ['Leia se o alvo sobe ou desce.', 'Acompanhe a altura com a mira.', 'Confirme o clique evitando um flick vertical maior que o movimento.'], 'Ficar olhando apenas a posição inicial.', 'Diminua os erros nas inversões e suba a dificuldade aos poucos.', '85% em pelo menos 15 tiros.', { accuracy: 85, shots: 15 }),
  floating_heads: guide(SKILL_TASKS.floating_heads.title, 'Punir a janela de aterrissagem de um drop.', ['Acompanhe a queda acelerada.', 'Espere o verde perto da aterrissagem.', 'Confirme o clique nessa janela.'], 'Atirar quando a cabeça ainda está alta.', 'Compare aterrissagens certas e alvos perdidos, mantendo a altura final prevista.', '80% em pelo menos 10 tentativas.', { accuracy: 80, shots: 10 }),
  popcorn: guide(SKILL_TASKS.popcorn.title, 'Ler a subida, o topo e a queda de um jump peek.', ['Acompanhe o alvo lançado com gravidade.', 'Observe a redução da velocidade vertical no topo.', 'Clique no topo verde para bônus ou confirme durante a queda.'], 'Clicar na trajetória anterior ou usar velocidade constante na queda.', 'Aumente o número de acertos no topo sem perder a precisão total.', '85% e pelo menos 3 acertos no topo.', { accuracy: 85, shots: 10, metric: 'apexHits', value: 3 }),
  tough_horizontal: guide(SKILL_TASKS.tough_horizontal.title, 'Confirmar tiros contra wide swings em hitboxes estreitas.', ['Acompanhe somente na horizontal.', 'Observe as mudanças de velocidade.', 'Confirme o tiro na parada brusca.'], 'Adicionar movimento vertical ou clicar antes da frenagem.', 'Treine em uma faixa de altura fixa e procure mais bônus de parada.', '85% e pelo menos 3 acertos na frenagem.', { accuracy: 85, shots: 15, metric: 'brakeHits', value: 3 }),
  pressure: guide(SKILL_TASKS.pressure.title, 'Combinar velocidade de microajuste com confirmação sob prazo curto.', ['Espere o spawn perto da mira.', 'Feche a pequena distância imediatamente.', 'Clique dentro da esfera antes que ela encolha e desapareça.'], 'Sacrificar confirmação para cumprir o prazo.', 'Comece com 350 ms e reduza perdas; erros descontam 250 pontos e zeram a sequência.', '80% em pelo menos 15 tentativas.', { accuracy: 80, shots: 15 }),
  underflick: guide(SKILL_TASKS.underflick.title, 'Separar aproximação e correção fina de forma consciente.', ['Parta da âncora central.', 'Faça o flick até a marca azul, antes da esfera, e estabilize brevemente.', 'Complete a microcorreção até a esfera e clique.'], 'Ir direto ao alvo, ignorando a etapa azul, ou parar longe demais.', 'Reduza a pausa entre as duas partes. A marca é visual; 1–2 cm no mousepad dependem da sua sensibilidade.', '95% em pelo menos 15 tiros válidos.', { accuracy: 95, shots: 15 }),
  angle_strafe: guide(SKILL_TASKS.angle_strafe.title, 'Compensar o deslocamento do personagem mantendo um pixel.', ['Segure A ou D e acompanhe a borda da coluna.', 'Inverta o lado regularmente.', 'Use o mouse para compensar sua própria movimentação.'], 'Ficar parado: a task só pontua enquanto você se desloca.', 'Amplie os strafes depois de manter cobertura; evite saltos da mira ao inverter.', '60% de cobertura e 10 inversões A/D.', { accuracy: 60, seconds: 30, metric: 'alternations', value: 10 }),
  pillars: guide(SKILL_TASKS.pillars.title, 'Sincronizar deslocamento, parada e clique.', ['Mova-se com WASD entre posições.', 'Solte ou inverta a direção para entrar na deadzone do jogo.', 'Confirme o alvo estreito e clique; depois reposicione-se.'], 'Atirar acima de 2,2 m/s ou no ar.', 'Observe o gráfico de erro de movimento; reduza tiros rejeitados antes de acelerar o ritmo.', '90% em pelo menos 15 tiros e até 2 tiros em movimento.', { accuracy: 90, shots: 15, maxMetric: 'movingShots', maxValue: 2 }),
  sens_overclock: guide(SKILL_TASKS.sens_overclock.title, 'Experimentar controle fino com uma sensibilidade temporariamente maior.', ['Escolha 1,5× ou 2×.', 'Treine microalvos com a mão leve, sem forçar a velocidade.', 'Volte à sens nativa e compare precisão e esforço.'], 'Tratar a sensação de estabilidade como prova automática de melhora.', 'Compare sessões na sens nativa antes/depois; mantenha a mesma dificuldade.', '90% em pelo menos 15 tiros. A sens nativa é restaurada ao sair.', { accuracy: 90, shots: 15 }),
  metronome_static: guide(SKILL_TASKS.metronome_static.title, 'Construir cadência uniforme em cliques confirmados.', ['Escolha 120, 130 ou 140 BPM.', 'Use o som ou a contagem visual das batidas.', 'Confirme um alvo e dê apenas um clique por batida.'], 'Fazer rajadas entre batidas; cliques fora da janela não pontuam.', 'Domine 120 BPM antes de subir. Compare o desvio médio em ms e a precisão.', '90% e 15 cliques no ritmo.', { accuracy: 90, shots: 15, metric: 'beatHits', value: 15 }),
  accuracy_floor: guide(SKILL_TASKS.accuracy_floor.title, 'Criar uma base de precisão antes de procurar pontuação ou velocidade.', ['Ignore o score e escolha um alvo por vez.', 'Clique somente após confirmar a mira.', 'Complete ao menos 20 tiros para validar a tentativa.'], 'Fazer só um acerto e encerrar com 100%.', 'Repita até atingir 95% em três rounds; acelere só se mantiver essa base.', '95% com pelo menos 20 tiros; sem isso, a sessão pede repetição.', { accuracy: 95, shots: 20 }),
  quiet_eye: guide(SKILL_TASKS.quiet_eye.title, 'Praticar observar primeiro, alinhar e só depois agir.', ['Observe o alvo antes de mover a mira (150 ms como referência do exercício).', 'Mantenha o retículo no alvo por 0,5 s, sem disparar.', 'Quando ficar verde, desvie com A/D por pelo menos 0,4 m.'], 'Confundir tempo da mira sobre o alvo com medição da fixação dos olhos.', 'Compare confirmações completas sem sobressalto. Leve a disciplina ao jogo, ajustando o tempo ao duelo real.', '10 confirmações seguidas de desvio. O jogo não rastreia seus olhos.', { kills: 10 }),
  dual_task: guide(SKILL_TASKS.dual_task.title, 'Praticar mira enquanto responde a estímulos secundários.', ['Mantenha os cliques nos microalvos.', 'Leia o estímulo no canto a cada 2 s.', 'Responda Q/E: azul/laranja, certo/errado na subtração, ou igual/diferente no 2-back.'], 'Parar completamente a mira para responder, ou ignorar a segunda tarefa.', 'Compare com uma sessão sem carga; só aumente a dificuldade se a precisão das duas tarefas se mantiver.', '85% de mira em 15 tiros e 70% nas respostas, com 10 respostas avaliáveis.', { accuracy: 85, shots: 15, cognitive: true }),
  target_blackout: guide(SKILL_TASKS.target_blackout.title, 'Antecipar uma trajetória durante a ausência temporária do alvo.', ['Observe a direção durante os 100 ms visíveis.', 'Continue acompanhando a trajetória invisível.', 'Confirme o clique na posição prevista; o alvo continua tendo hitbox.'], 'Esperar parado até reaparecer ou adivinhar sem ler a velocidade.', 'Compare precisão com Tough Horizontal; use trajetórias mais lentas antes de aumentar a dificuldade.', '70% em pelo menos 15 tiros.', { accuracy: 70, shots: 15 }),
  no_crosshair: guide(SKILL_TASKS.no_crosshair.title, 'Observar a referência do centro da tela sem o desenho da mira.', ['Olhe os alvos na linha dos olhos.', 'Leve o centro da visão até a esfera.', 'Confirme e clique; a mira gráfica volta ao sair.'], 'Usar a ponta da arma como referência fixa do tiro.', 'Compare com Horizontal Clicking usando mira normal; mantenha a mesma sensibilidade.', '85% em pelo menos 15 tiros.', { accuracy: 85, shots: 15 }),
  sens_calibration: guide(SKILL_TASKS.sens_calibration.title, 'Comparar microcontrole, amplitude e retorno à sens nativa.', ['Micro: 5 min a 2×, com pequenos alvos.', 'Amplitude: 5 min a 0,5×, com alvos distribuídos ao redor da posição inicial.', 'Nativa: 5 min a 1×, comparando o controle após a variação.'], 'Comparar scores de fases diferentes como se fossem o mesmo teste.', 'Observe precisão e conforto na fase nativa; a sequência é experimental, não uma garantia de ganho.', '90% em pelo menos 15 tiros na fase nativa.', { accuracy: 90, shots: 15 }),
  breath_reset: guide(SKILL_TASKS.breath_reset.title, 'Criar uma pausa entre rounds para perceber e reduzir tensão voluntária da mão.', ['Solte os ombros, os dedos e a pressão no mouse.', 'Respire confortavelmente acompanhando as instruções.', 'Retome um round fácil e compare o controle.'], 'Forçar respiração, prender o ar ou usar a pausa como teste de desempenho.', 'Use antes de uma rotina ou após um round tenso. Suspiro cíclico pode ser explorado fora do jogo: duas inspirações leves e uma expiração confortável, sem esforço.', 'Pausa de 30 s; sem pontuação ou avaliação fisiológica.', { seconds: 30, rest: true })
});

const stage = (mode, time = 60, variant, desc) => ({ mode, time, variant, title: TASK_GUIDES[mode].title,
  tag: 'TREINO GUIADO', desc: desc || TASK_GUIDES[mode].steps.join(' ') });
const routine = (id, title, purpose, stages) => ({ id, title, badge: 'ROTINA GUIADA', badgeColor: '#70d9ef', guided: true,
  desc: purpose, stages });
export const GUIDED_PLAYLISTS = Object.freeze({
  learn_basics: routine('learn_basics', 'BASE DE PRIMEIRO TIRO', 'Observe, aproxime, corrija e confirme. Repita mantendo precisão antes de acelerar.', [stage('quiet_eye'), stage('underflick'), stage('accuracy_floor'), stage('metronome_static', 60, '120'), stage('pressure'), stage('breath_reset', 30)]),
  learn_horizontal: routine('learn_horizontal', 'ANTI-PEEKING HORIZONTAL', 'Do ADAD curto ao wide swing: mantenha a altura e confirme a frenagem.', [stage('horizontal_clicking'), stage('tough_horizontal'), stage('pressure'), stage('hold_pixel'), stage('voxts')]),
  learn_movement: routine('learn_movement', 'TECLADO + MOUSE', 'Compense seu strafe, entre na deadzone e confirme o tiro; finalize desviando de projéteis.', [stage('angle_strafe'), stage('pillars'), stage('tracking'), stage('drones')]),
  learn_vertical: routine('learn_vertical', 'JUMP PEEK & ATERRISSAGEM', 'Leia subida, topo, queda e slide; cada altura pede um ajuste diferente.', [stage('popcorn'), stage('floating_heads'), stage('vertical_strafes'), stage('jett_neon')]),
  learn_attention: routine('learn_attention', 'ATENÇÃO & ANTECIPAÇÃO', 'Compare leitura periférica, subtração, memória de dois passos e tracking oculto.', [stage('dual_task', 60, 'peripheral'), stage('dual_task', 60, 'serial'), stage('dual_task', 60, 'nback'), stage('target_blackout'), stage('quiet_eye')]),
  learn_overclock: routine('learn_overclock', 'OVERCLOCK • 10 MIN + RETORNO', 'Microcontrole a 1,5× por 10 min; depois, retorno automático à sens normal para comparar.', [stage('sens_overclock', 600, 'one_half'), stage('wall_two'), stage('accuracy_floor')]),
  learn_calibration: routine('learn_calibration', 'HIPERDIFERENCIAL • 15 MIN', 'Cinco minutos por fase: 2× micro, 0,5× amplitude e 1× nativa. Compare controle, não os scores entre fases.', [stage('sens_calibration', 300, 'high'), stage('sens_calibration', 300, 'low'), stage('sens_calibration', 300, 'native')]),
  learn_discipline: routine('learn_discipline', 'DISCIPLINA VISUAL & 95%', 'Sem mira gráfica, sem disparar e com cadência; termine confirmando 95% de precisão.', [stage('no_crosshair'), stage('quiet_eye', 600), stage('metronome_static', 60, '130'), stage('accuracy_floor')]),
  learn_site: routine('learn_site', 'DEFESA DE SITE', 'Combine reação, utilidades, movimento e leitura de passagens.', [stage('hold_pixel'), stage('anti_rush', 90), stage('drones'), stage('jett_neon'), stage('breath_reset', 30)]),
  learn_complete: routine('learn_complete', 'CURSO COMPLETO • TODAS AS TASKS', 'Uma passagem por todas as 35 tasks. Consulte os guias e use as rotinas menores para repetir o ponto mais fraco.', Object.keys(TASK_GUIDES).map(mode => stage(mode, mode === 'breath_reset' ? 30 : 45, SKILL_TASKS[mode]?.variants?.[0][0])))
});

export function assessTraining(summary) {
  const lesson = TASK_GUIDES[summary.mode]; if (!lesson) return null;
  const goal = lesson.target, metrics = summary.skillMetrics || {}, shots = (summary.hits || 0) + (summary.misses || 0);
  const seconds = summary.elapsedSeconds ?? metrics.sampleTime ?? 0;
  const coverage = summary.mode === 'voltaic_smooth' ? summary.trackingCoverage : summary.accuracy;
  const automatic = metrics.automatic;
  const measuredAccuracy = goal.shots && shots > 0 && !automatic ? 100 * (summary.hits || 0) / shots : coverage;
  const enoughShots = goal.autoOrClick && automatic ? true : !goal.shots || shots >= goal.shots;
  const enoughTime = goal.autoOrClick && !automatic ? true : !goal.seconds || seconds >= goal.seconds;
  const cognitive = !goal.cognitive || (metrics.cognitiveTrials >= 10 && metrics.cognitiveHits / metrics.cognitiveTrials >= .7);
  const accuracyGoal = goal.autoOrClick && !automatic ? 85 : goal.accuracy;
  const passed = enoughShots && enoughTime && (!accuracyGoal || measuredAccuracy >= accuracyGoal) &&
    (!goal.kills || (summary.headshots || 0) >= goal.kills) && (!goal.victory || summary.isVictory) &&
    (!goal.metric || metrics[goal.metric] >= goal.value) && (!goal.maxMetric || metrics[goal.maxMetric] <= goal.maxValue) && cognitive;
  return { passed, practiceOnly: !!goal.rest, goal: lesson.goal, metricsText: describeTrainingMetrics(summary),
    feedback: goal.rest ? 'Pausa concluída. Observe o conforto ao voltar ao treino.' : passed ? `Meta atingida. ${lesson.improve}` :
      !enoughShots || !enoughTime ? `Complete uma amostra maior antes de avaliar. ${lesson.goal}` :
      !cognitive ? 'A carga cognitiva ainda está alta. Repita no Fácil e mantenha as duas tarefas.' : `${lesson.improve} Evite: ${lesson.mistake}` };
}

export function describeTrainingMetrics(summary) {
  const metrics = summary.skillMetrics || {}, parts = [];
  if (summary.mode === 'popcorn') parts.push(`${metrics.apexHits || 0} acertos no topo`);
  if (summary.mode === 'tough_horizontal') parts.push(`${metrics.brakeHits || 0} acertos na frenagem`);
  if (summary.mode === 'pillars') parts.push(`${metrics.movingShots || 0} tiros em movimento`);
  if (summary.mode === 'angle_strafe') parts.push(`${metrics.alternations || 0} inversões A/D`);
  if (summary.mode === 'metronome_static') parts.push(`${metrics.beatHits || 0} cliques no ritmo`, `desvio médio: ${metrics.beatError == null ? '—' : metrics.beatError} ms`);
  if (summary.mode === 'dual_task') parts.push(`${metrics.cognitiveHits || 0}/${metrics.cognitiveTrials || 0} respostas corretas`, `${metrics.cognitiveMisses || 0} erradas/perdidas`);
  if (metrics.automatic && summary.mode !== 'breath_reset') parts.push(`${summary.accuracy || 0}% de cobertura`);
  return parts.join(' • ');
}

export const TRAINING_METHODS = [
  ['Como usar o ensino', 'Leia o objetivo e os três passos, faça um round Fácil e veja o feedback. Repita a mesma variante até cumprir a meta em três sessões; depois aumente uma variável por vez. As metas são critérios locais deste jogo, não benchmarks oficiais.'],
  ['Quiet Eye e eye-lead', 'Observe o alvo antes do mouse e use 150 ms como referência de prática, sem contar durante um duelo. No treino sem disparo, confirme 0,5 s e desvie. A task mede o retículo, não a fixação ocular; não transfira a espera de 0,5 s literalmente para um duelo competitivo.'],
  ['Sensibilidade alterada', 'Overclock usa 1,5× ou 2× temporários. A rotina hiperdiferencial usa 5 min a 2×, 5 min a 0,5× e 5 min na sens original. Compare precisão na fase nativa e mantenha apenas o que ajuda seu controle.'],
  ['Cadência e Accuracy Floor', 'O metrônomo oferece 120–140 BPM e uma janela de clique. Accuracy Floor requer 95% e pelo menos 20 tiros; aumente a velocidade depois de manter a base, não por perseguir score.'],
  ['Dupla tarefa', 'Q/E responde sem soltar o mouse: azul/laranja; resultado correto/incorreto de uma subtração de 7; igual/diferente ao número de dois passos atrás. A tarefa mostra precisão motora e cognitiva separadas. Para prática verbal externa, você também pode contar 100, 93, 86… em voz alta.'],
  ['Respiração, tensão e fadiga', 'Use Reset entre rounds como pausa de 30–60 s e respire sem forçar. O jogo não mede pulso, cortisol ou tónus vagal. Exercícios físicos antes do treino são opcionais e não fazem parte da validação; não é necessário executar burpees ou flexões para usar as rotinas.'],
  ['Oclusão visual', 'No Crosshair oculta só a mira gráfica; Target Blackout mostra o alvo por 100 ms a cada ciclo de 800 ms, mantendo a trajetória e a hitbox. Não há flashes de tela ou filtro estroboscópico. Compare com a mesma task visível para avaliar a antecipação.'],
  ['Como avaliar melhora', 'Use a mesma sens nativa, variante, dificuldade e duração para comparar rounds. Observe acertos, perdas, cobertura, tiros em movimento, ritmo e respostas secundárias. Sensação de facilidade e recorde isolado não demonstram transferência automática para partidas.']
];
export const TRAINING_SOURCES = [
  ['Pesquisa sobre Quiet Eye em tarefas de FPS', 'https://www.frontiersin.org/journals/psychology/articles/10.3389/fpsyg.2021.676591/full'],
  ['Aimlabs: relação entre velocidade e precisão', 'https://aimlabs.com/articles/aimlabs/the-speed-accuracy-tradeoff-and-what-it-means-for-your-aim-training/'],
  ['Aimlabs: variação de sensibilidade no treino', 'https://aimlabs.com/articles/aimlabs/why-changing-your-sensitivity-can-actually-help-you-train/'],
  ['Estudo sobre práticas breves de respiração', 'https://pubmed.ncbi.nlm.nih.gov/36630953/']
];
